name: Feature Request
description: Suggest an idea for @lapidist/design-lint
title: '[Feature]: '
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve @lapidist/design-lint!
        Please search existing issues before filing a new request.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What feature would you like to see?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important? What problem does it solve?
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe how you think this should work.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, references, or any additional details.
